---
# pre-commit configuration for cdot65.scm collection
# To install: pre-commit install
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 25.3.0
    hooks:
      - id: black
        args: [--line-length=128]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length=128"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [check, --fix, --exit-non-zero-on-fix]
        exclude: ^plugins/module_utils/.*\.py$
      - id: ruff-format
        exclude: ^plugins/module_utils/.*\.py$
        
  - repo: local
    hooks:
      - id: quality
        name: Format plugins with ruff and run flake8 and mypy
        entry: make quality
        language: system
        pass_filenames: false
        types: [python]
        files: ^plugins/

  - repo: https://github.com/ansible-community/ansible-lint
    rev: v24.2.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$