---
# Example playbook for managing folders in Strata Cloud Manager
# Usage: poetry run ansible-playbook docs/examples/folder_management.yml -e "api_key=your_api_key api_url=your_api_url"

- name: SCM Folder Management Example
  hosts: localhost
  gather_facts: false
  collections:
    - cdot65.scm
  vars:
    api_key: "{{ api_key }}"
    api_url: "{{ api_url }}"
    # Alternatively, set SCM_API_KEY and SCM_API_URL environment variables

  tasks:
    - name: Get all folders
      folder_info:
        api_key: "{{ api_key }}"
        api_url: "{{ api_url }}"
      register: all_folders
      
    - name: Display all folders
      debug:
        var: all_folders.folders
      
    - name: Create a parent folder
      folder:
        api_key: "{{ api_key }}"
        api_url: "{{ api_url }}"
        name: "Network Objects"
        description: "Parent folder for network objects"
        state: present
      register: parent_folder
      
    - name: Create a child folder
      folder:
        api_key: "{{ api_key }}"
        api_url: "{{ api_url }}"
        name: "Address Objects"
        description: "Folder for address objects"
        parent_folder_id: "{{ parent_folder.folder.id }}"
        state: present
      register: child_folder
      
    - name: Get specific folder by ID
      folder_info:
        api_key: "{{ api_key }}"
        api_url: "{{ api_url }}"
        folder_id: "{{ child_folder.folder.id }}"
      register: folder_details
      
    - name: Display folder details
      debug:
        var: folder_details.folders
