---
# Authentication parameters with more flexible environment variable handling
scm_client_id: "{{ lookup('env', 'CLIENT_ID') | default(lookup('env', 'SCM_CLIENT_ID'), true) | default('') }}"
scm_client_secret: "{{ lookup('env', 'CLIENT_SECRET') | default(lookup('env', 'SCM_CLIENT_SECRET'), true) | default('') }}"
scm_tsg_id: "{{ lookup('env', 'TSG_ID') | default(lookup('env', 'SCM_TSG_ID'), true) | default('') }}"
scm_api_base_url: "{{ lookup('env', 'API_BASE_URL') | default(lookup('env', 'SCM_API_BASE_URL'), true) | default('https://api.strata.paloaltonetworks.com') }}"
scm_token_url: "{{ lookup('env', 'TOKEN_URL') | default(lookup('env', 'SCM_TOKEN_URL'), true) | default('https://auth.apps.paloaltonetworks.com/am/oauth2/access_token') }}"
scm_log_level: "{{ lookup('env', 'LOG_LEVEL') | default(lookup('env', 'SCM_LOG_LEVEL'), true) | default('ERROR') }}"

# Option to store token in a file for long-running sessions
scm_save_token: false
scm_token_path: "~/.scm_token.json"
