---
- name: Authenticate with SCM using the auth role
  hosts: localhost
  gather_facts: no
  roles:
    - cdot65.scm.auth
  vars_files:
    - ../vault.yml

- name: Query SCM folder information using the established session
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display authentication info
      debug:
        msg: "Authenticated with token: {{ scm_access_token | default('No token available!', true) | truncate(15, true, '...') }}"

    - name: Create a label
      cdot65.scm.label:
        name: environment
        description: Environment classification label
        scm_access_token: "{{ scm_access_token }}"
      register: environment_label

    - name: Show environment label info
      debug:
        var: environment_label

    - name: Get all labels
      cdot65.scm.label_info:
        scm_access_token: "{{ scm_access_token }}"
      register: all_labels

    - name: Show all label info
      debug:
        var: all_labels

#    - name: Get a specific label by ID
#      cdot65.scm.label_info:
#        id: "123e4567-e89b-12d3-a456-426655440000"
#        scm_access_token: "{{ scm_access_token }}"
#      register: label_details

    - name: Get a specific label by name
      cdot65.scm.label_info:
        name: "environment"
        scm_access_token: "{{ scm_access_token }}"
      register: named_label

    - name: Show named label info
      debug:
        var: named_label

    - name: Remove a label
      cdot65.scm.label:
        name: "environment"
        scm_access_token: "{{ scm_access_token }}"
        state: absent
