---
# Example playbook for retrieving application information in Strata Cloud Manager
# This playbook demonstrates various ways to query applications

- name: Authenticate with SCM using the auth role
  hosts: localhost
  gather_facts: no
  roles:
    - cdot65.scm.auth
  vars_files:
    - ../vault.yml

- name: Query SCM application information using the established session
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display authentication info
      debug:
        msg: "Authenticated with token: {{ scm_access_token | default('No token available!', true) | truncate(15, true, '...') }}"

    # Create test resources for demonstration
    - name: Create a test folder
      cdot65.scm.folder:
        name: "App-Test-Folder"
        parent: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    - name: Create a test snippet
      cdot65.scm.snippet:
        name: "App-Test-Snippet"
        description: "Snippet for testing applications"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    # Create applications for testing
    - name: Create a business application
      cdot65.scm.application:
        name: "business-app-1"
        description: "Business application for testing"
        category: "business-systems"
        subcategory: "management"
        technology: "client-server"
        risk: 3
        ports:
          - "tcp/8080"
        folder: "App-Test-Folder"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    - name: Create a file-sharing application
      cdot65.scm.application:
        name: "file-sharing-app-1"
        description: "file-sharing application for testing"
        category: "general-internet"
        subcategory: "file-sharing"
        technology: "browser-based"
        risk: 2
        folder: "App-Test-Folder"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    - name: Create a high-risk application
      cdot65.scm.application:
        name: "high-risk-app"
        description: "High risk application for testing"
        category: "media"
        subcategory: "photo-video"
        technology: "peer-to-peer"
        risk: 5
        snippet: "App-Test-Snippet"
        excessive_bandwidth_use: true
        transfers_files: true
        has_known_vulnerabilities: true
        scm_access_token: "{{ scm_access_token }}"
        state: present

    # Filter by container - folder
    - name: Get applications in a specific folder
      cdot65.scm.application_info:
        folder: "App-Test-Folder"
        scm_access_token: "{{ scm_access_token }}"
      register: folder_apps

    - name: Display folder applications
      ansible.builtin.debug:
        var: folder_apps.applications

    # Filter by container - snippet
    - name: Get applications in a specific snippet
      cdot65.scm.application_info:
        snippet: "App-Test-Snippet"
        scm_access_token: "{{ scm_access_token }}"
      register: snippet_apps
      
    - name: Display snippet applications
      ansible.builtin.debug:
        var: snippet_apps.applications

    # Filter by category
    - name: Get business system applications
      cdot65.scm.application_info:
        category: ["business-systems"]
        folder: "App-Test-Folder"
        scm_access_token: "{{ scm_access_token }}"
      register: business_apps
      
    - name: Display business applications
      ansible.builtin.debug:
        var: business_apps.applications

    # Filter by subcategory
    - name: Get file sharing applications
      cdot65.scm.application_info:
        subcategory: ["file-sharing"]
        folder: "App-Test-Folder"
        scm_access_token: "{{ scm_access_token }}"
      register: file_sharing_apps
      
    - name: Display file sharing applications
      ansible.builtin.debug:
        var: file_sharing_apps.applications

    # Filter by technology
    - name: Get peer-to-peer applications
      cdot65.scm.application_info:
        technology: ["peer-to-peer"]
        snippet: "App-Test-Snippet"
        scm_access_token: "{{ scm_access_token }}"
      register: p2p_apps
      
    - name: Display peer-to-peer applications
      ansible.builtin.debug:
        var: p2p_apps.applications

    # Filter by risk level
    - name: Get high risk applications (risk 4-5)
      cdot65.scm.application_info:
        risk: [4, 5]
        snippet: "App-Test-Snippet"
        scm_access_token: "{{ scm_access_token }}"
      register: high_risk_apps
      
    - name: Display high risk applications
      ansible.builtin.debug:
        var: high_risk_apps.applications

    # Get a specific application by name (requires container parameter)
    - name: Get specific application by name in folder
      cdot65.scm.application_info:
        name: "business-app-1"
        folder: "App-Test-Folder"  # Container parameter is required when using name
        scm_access_token: "{{ scm_access_token }}"
      register: specific_folder_app
      
    - name: Display specific folder application details
      ansible.builtin.debug:
        var: specific_folder_app.applications
      when: specific_folder_app.applications | length > 0

    # Get a specific application by name in snippet
    - name: Get specific application by name in snippet
      cdot65.scm.application_info:
        name: "high-risk-app"
        snippet: "App-Test-Snippet"  # Container parameter is required when using name
        scm_access_token: "{{ scm_access_token }}"
      register: specific_snippet_app
      
    - name: Display specific snippet application details
      ansible.builtin.debug:
        var: specific_snippet_app.applications
      when: specific_snippet_app.applications | length > 0

    # Cleanup
    - name: Delete applications from folder
      cdot65.scm.application:
        name: "{{ item }}"
        folder: "App-Test-Folder"
        scm_access_token: "{{ scm_access_token }}"
        state: absent
      loop:
        - "business-app-1"
        - "file-sharing-app-1"

    - name: Delete applications from snippet
      cdot65.scm.application:
        name: "high-risk-app"
        snippet: "App-Test-Snippet"
        scm_access_token: "{{ scm_access_token }}"
        state: absent

    - name: Delete test folder
      cdot65.scm.folder:
        name: "App-Test-Folder"
        parent: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: absent

    - name: Delete test snippet
      cdot65.scm.snippet:
        name: "App-Test-Snippet"
        scm_access_token: "{{ scm_access_token }}"
        state: absent