---
# Example playbook for retrieving bandwidth allocation information from Strata Cloud Manager

- name: Bandwidth Allocation Info Examples
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yml

  tasks:
    # Setup authentication
    - name: Authenticate with SCM
      ansible.builtin.include_role:
        name: cdot65.scm.auth
      vars:
        client_id: "{{ scm_client_id }}"
        client_secret: "{{ scm_client_secret }}"
        tsg_id: "{{ scm_tsg_id }}"

    # List all bandwidth allocations
    - name: List all bandwidth allocations
      cdot65.scm.bandwidth_allocation_info:
        scm_access_token: "{{ scm_access_token }}"
      register: all_allocations

    - name: Display all allocations
      ansible.builtin.debug:
        var: all_allocations.allocations

    # Get specific bandwidth allocation
    - name: Get specific bandwidth allocation by name
      cdot65.scm.bandwidth_allocation_info:
        name: "Example-Region-East"
        scm_access_token: "{{ scm_access_token }}"
      register: specific_allocation

    - name: Display specific allocation
      ansible.builtin.debug:
        var: specific_allocation.allocations
