---
# Example playbook for retrieving security rule information from Strata Cloud Manager (SCM)
# This playbook demonstrates various ways to query security rules

- name: Security Rule Info Examples
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vault.yml  # Contains scm_client_id, scm_client_secret, scm_tsg_id
  vars:
    cleanup_security_resources: false  # Set to true to cleanup all created resources

  tasks:
    # =========================================================================
    # Authentication
    # =========================================================================
    - name: Authenticate with SCM
      ansible.builtin.include_role:
        name: cdot65.scm.auth
      vars:
        client_id: "{{ scm_client_id }}"
        client_secret: "{{ scm_client_secret }}"
        tsg_id: "{{ scm_tsg_id }}"

    # =========================================================================
    # Create Tags
    # =========================================================================
    - name: Create Production tag
      cdot65.scm.tag:
        name: "info-Production"
        color: "Red"
        comments: "Production environment resources for info examples"
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    - name: Create Security tag
      cdot65.scm.tag:
        name: "info-Security"
        color: "Orange"
        comments: "Security-related resources for info examples"
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    - name: Create Web-Tier tag
      cdot65.scm.tag:
        name: "info-Web-Tier"
        color: "Green"
        comments: "Web tier resources for info examples"
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    # =========================================================================
    # Create Address Objects
    # Note: Using predefined security zones (dia, mpls, lan, dmz)
    # =========================================================================
    - name: Create web-server-1 address
      cdot65.scm.address:
        name: "info-web-server-1"
        description: "Primary web server for info examples"
        ip_netmask: "192.168.10.10/32"
        folder: "Texas"
        tag:
          - "info-Web-Tier"
          - "info-Production"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    - name: Create web-server-2 address
      cdot65.scm.address:
        name: "info-web-server-2"
        description: "Secondary web server for info examples"
        ip_netmask: "192.168.10.11/32"
        folder: "Texas"
        tag:
          - "info-Web-Tier"
          - "info-Production"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    - name: Create internal-network address
      cdot65.scm.address:
        name: "info-internal-network"
        description: "Internal corporate network for info examples"
        ip_netmask: "10.0.0.0/8"
        folder: "Texas"
        tag:
          - "info-Production"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    # =========================================================================
    # Create Address Groups
    # =========================================================================
    - name: Create web-servers address group
      cdot65.scm.address_group:
        name: "info-web-servers"
        static_addresses:
          - "info-web-server-1"
          - "info-web-server-2"
        folder: "Texas"
        tag:
          - "info-Web-Tier"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    # =========================================================================
    # Create Service Objects
    # =========================================================================
    - name: Create service-http
      cdot65.scm.service:
        name: "info-http"
        description: "HTTP service for info examples"
        protocol:
          tcp:
            port: "80"
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    - name: Create service-https
      cdot65.scm.service:
        name: "info-https"
        description: "HTTPS service for info examples"
        protocol:
          tcp:
            port: "443"
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    # =========================================================================
    # Create Service Groups
    # =========================================================================
    - name: Create web-services service group
      cdot65.scm.service_group:
        name: "info-web-services"
        members:
          - "info-http"
          - "info-https"
        folder: "Texas"
        tag:
          - "info-Web-Tier"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    # =========================================================================
    # Create Test Security Rules
    # =========================================================================
    - name: Create allow web traffic rule
      cdot65.scm.security_rule:
        name: "Info-Allow-Web-Traffic"
        description: "Allow web traffic for info query examples"
        from_:
          - "lan"
        to_:
          - "dmz"
        source:
          - "info-internal-network"
        destination:
          - "info-web-servers"
        application:
          - "web-browsing"
          - "ssl"
        service:
          - "info-web-services"
        action: "allow"
        log_end: true
        folder: "Texas"
        rulebase: "pre"
        tag:
          - "info-Production"
          - "info-Web-Tier"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    - name: Create deny rule
      cdot65.scm.security_rule:
        name: "Info-Block-Traffic"
        description: "Block traffic for info query examples"
        from_:
          - "dia"
        to_:
          - "lan"
        source:
          - "any"
        destination:
          - "any"
        application:
          - "any"
        service:
          - "any"
        action: "deny"
        log_end: true
        folder: "Texas"
        rulebase: "pre"
        tag:
          - "info-Security"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    - name: Create disabled rule
      cdot65.scm.security_rule:
        name: "Info-Disabled-Rule"
        description: "Disabled rule for info query examples"
        from_:
          - "any"
        to_:
          - "any"
        source:
          - "any"
        destination:
          - "any"
        application:
          - "any"
        service:
          - "any"
        action: "allow"
        disabled: true
        folder: "Texas"
        rulebase: "pre"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    - name: Create post-rulebase cleanup rule
      cdot65.scm.security_rule:
        name: "Info-Cleanup-Rule"
        description: "Post-rulebase catch-all for info examples"
        from_:
          - "any"
        to_:
          - "any"
        source:
          - "any"
        destination:
          - "any"
        application:
          - "any"
        service:
          - "any"
        action: "deny"
        log_end: true
        folder: "Texas"
        rulebase: "post"
        scm_access_token: "{{ scm_access_token }}"
        state: present

    # =========================================================================
    # List Security Rules
    # =========================================================================
    - name: Get all security rules in pre-rulebase
      cdot65.scm.security_rule_info:
        folder: "Texas"
        rulebase: "pre"
        scm_access_token: "{{ scm_access_token }}"
      register: all_pre_rules

    - name: Display all pre-rulebase rules
      ansible.builtin.debug:
        msg: "Found {{ all_pre_rules.security_rules | length }} security rules in pre-rulebase"

    - name: Display rule names in pre-rulebase
      ansible.builtin.debug:
        msg: "{{ item.name }}"
      loop: "{{ all_pre_rules.security_rules }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Get all security rules in post-rulebase
      cdot65.scm.security_rule_info:
        folder: "Texas"
        rulebase: "post"
        scm_access_token: "{{ scm_access_token }}"
      register: all_post_rules

    - name: Display all post-rulebase rules
      ansible.builtin.debug:
        msg: "Found {{ all_post_rules.security_rules | length }} security rules in post-rulebase"

    # =========================================================================
    # Get Specific Rule by Name
    # =========================================================================
    - name: Get a specific security rule by name
      cdot65.scm.security_rule_info:
        name: "Info-Allow-Web-Traffic"
        folder: "Texas"
        rulebase: "pre"
        scm_access_token: "{{ scm_access_token }}"
      register: named_rule
      ignore_errors: true

    - name: Display named rule details
      ansible.builtin.debug:
        var: named_rule.security_rules
      when: named_rule.security_rules is defined and named_rule.security_rules | length > 0

    # =========================================================================
    # Filter Security Rules
    # =========================================================================
    - name: Get all allow rules
      cdot65.scm.security_rule_info:
        action: ["allow"]
        folder: "Texas"
        rulebase: "pre"
        scm_access_token: "{{ scm_access_token }}"
      register: allow_rules

    - name: Display allow rules count
      ansible.builtin.debug:
        msg: "Found {{ allow_rules.security_rules | length }} allow rules"

    - name: Get all deny rules
      cdot65.scm.security_rule_info:
        action: ["deny"]
        folder: "Texas"
        rulebase: "pre"
        scm_access_token: "{{ scm_access_token }}"
      register: deny_rules

    - name: Display deny rules count
      ansible.builtin.debug:
        msg: "Found {{ deny_rules.security_rules | length }} deny rules"

    - name: Get rules with specific tags
      cdot65.scm.security_rule_info:
        tags: ["info-Production"]
        folder: "Texas"
        rulebase: "pre"
        scm_access_token: "{{ scm_access_token }}"
      register: tagged_rules
      ignore_errors: true

    - name: Display tagged rules
      ansible.builtin.debug:
        msg: "Found {{ tagged_rules.security_rules | length }} rules with 'info-Production' tag"
      when: tagged_rules.security_rules is defined

    - name: Get rules matching specific source zone
      cdot65.scm.security_rule_info:
        from_: ["lan"]
        folder: "Texas"
        rulebase: "pre"
        scm_access_token: "{{ scm_access_token }}"
      register: lan_zone_rules

    - name: Display lan zone rules
      ansible.builtin.debug:
        msg: "Found {{ lan_zone_rules.security_rules | length }} rules from 'lan' zone"

    - name: Get rules matching specific destination zone
      cdot65.scm.security_rule_info:
        to_: ["dmz"]
        folder: "Texas"
        rulebase: "pre"
        scm_access_token: "{{ scm_access_token }}"
      register: dmz_zone_rules

    - name: Display dmz zone rules
      ansible.builtin.debug:
        msg: "Found {{ dmz_zone_rules.security_rules | length }} rules to 'dmz' zone"

    - name: Get rules for specific applications
      cdot65.scm.security_rule_info:
        application: ["web-browsing", "ssl"]
        folder: "Texas"
        rulebase: "pre"
        scm_access_token: "{{ scm_access_token }}"
      register: web_app_rules

    - name: Display web application rules
      ansible.builtin.debug:
        msg: "Found {{ web_app_rules.security_rules | length }} rules for web applications"

    - name: Get disabled rules
      cdot65.scm.security_rule_info:
        disabled: true
        folder: "Texas"
        rulebase: "pre"
        scm_access_token: "{{ scm_access_token }}"
      register: disabled_rules

    - name: Display disabled rules count
      ansible.builtin.debug:
        msg: "Found {{ disabled_rules.security_rules | length }} disabled rules"

    - name: Get enabled rules
      cdot65.scm.security_rule_info:
        disabled: false
        folder: "Texas"
        rulebase: "pre"
        scm_access_token: "{{ scm_access_token }}"
      register: enabled_rules

    - name: Display enabled rules count
      ansible.builtin.debug:
        msg: "Found {{ enabled_rules.security_rules | length }} enabled rules"

    # =========================================================================
    # Display Summary
    # =========================================================================
    - name: Display security rules summary
      ansible.builtin.debug:
        msg:
          - "=== Security Rules Summary ==="
          - "Pre-rulebase rules: {{ all_pre_rules.security_rules | length }}"
          - "Post-rulebase rules: {{ all_post_rules.security_rules | length }}"
          - "Allow rules: {{ allow_rules.security_rules | length }}"
          - "Deny rules: {{ deny_rules.security_rules | length }}"
          - "LAN zone rules: {{ lan_zone_rules.security_rules | length }}"
          - "DMZ zone rules: {{ dmz_zone_rules.security_rules | length }}"
          - "Disabled rules: {{ disabled_rules.security_rules | length }}"
          - "Enabled rules: {{ enabled_rules.security_rules | length }}"

    # =========================================================================
    # Conditional Cleanup (run with -e cleanup_security_resources=true)
    # =========================================================================
    - name: Delete security rules
      when: cleanup_security_resources | default(false) | bool
      block:
        - name: Delete Info-Allow-Web-Traffic rule
          cdot65.scm.security_rule:
            name: "Info-Allow-Web-Traffic"
            folder: "Texas"
            rulebase: "pre"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

        - name: Delete Info-Block-Traffic rule
          cdot65.scm.security_rule:
            name: "Info-Block-Traffic"
            folder: "Texas"
            rulebase: "pre"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

        - name: Delete Info-Disabled-Rule
          cdot65.scm.security_rule:
            name: "Info-Disabled-Rule"
            folder: "Texas"
            rulebase: "pre"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

        - name: Delete Info-Cleanup-Rule
          cdot65.scm.security_rule:
            name: "Info-Cleanup-Rule"
            folder: "Texas"
            rulebase: "post"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

    - name: Delete service groups
      when: cleanup_security_resources | default(false) | bool
      block:
        - name: Delete info-web-services service group
          cdot65.scm.service_group:
            name: "info-web-services"
            folder: "Texas"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

    - name: Delete service objects
      when: cleanup_security_resources | default(false) | bool
      block:
        - name: Delete info-http
          cdot65.scm.service:
            name: "info-http"
            folder: "Texas"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

        - name: Delete info-https
          cdot65.scm.service:
            name: "info-https"
            folder: "Texas"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

    - name: Delete address groups
      when: cleanup_security_resources | default(false) | bool
      block:
        - name: Delete info-web-servers address group
          cdot65.scm.address_group:
            name: "info-web-servers"
            folder: "Texas"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

    - name: Delete address objects
      when: cleanup_security_resources | default(false) | bool
      block:
        - name: Delete info-web-server-1 address
          cdot65.scm.address:
            name: "info-web-server-1"
            folder: "Texas"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

        - name: Delete info-web-server-2 address
          cdot65.scm.address:
            name: "info-web-server-2"
            folder: "Texas"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

        - name: Delete info-internal-network address
          cdot65.scm.address:
            name: "info-internal-network"
            folder: "Texas"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

    - name: Delete tags
      when: cleanup_security_resources | default(false) | bool
      block:
        - name: Delete info-Production tag
          cdot65.scm.tag:
            name: "info-Production"
            folder: "Texas"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

        - name: Delete info-Security tag
          cdot65.scm.tag:
            name: "info-Security"
            folder: "Texas"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

        - name: Delete info-Web-Tier tag
          cdot65.scm.tag:
            name: "info-Web-Tier"
            folder: "Texas"
            scm_access_token: "{{ scm_access_token }}"
            state: absent

    - name: Display cleanup completion message
      when: cleanup_security_resources | default(false) | bool
      ansible.builtin.debug:
        msg: "All security rule info test resources have been cleaned up successfully"
