---
# Example playbook for retrieving URL category information from Strata Cloud Manager (SCM)
# This playbook demonstrates various ways to query custom URL categories

- name: URL Categories Info Examples
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yml  # Contains scm_client_id, scm_client_secret, scm_tsg_id

  tasks:
    # =========================================================================
    # Authentication
    # =========================================================================
    - name: Authenticate with SCM
      ansible.builtin.include_role:
        name: cdot65.scm.auth
      vars:
        client_id: "{{ scm_client_id }}"
        client_secret: "{{ scm_client_secret }}"
        tsg_id: "{{ scm_tsg_id }}"

    # =========================================================================
    # List URL Categories
    # =========================================================================
    - name: Get all URL categories in folder
      cdot65.scm.url_categories_info:
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
      register: all_url_categories

    - name: Display all URL categories
      ansible.builtin.debug:
        msg: "Found {{ all_url_categories.url_categories | length }} URL categories"

    - name: Display URL category names and entry counts
      ansible.builtin.debug:
        msg: "{{ item.name }}: {{ item.list | length }} entries ({{ item.type }})"
      loop: "{{ all_url_categories.url_categories }}"
      loop_control:
        label: "{{ item.name }}"

    # =========================================================================
    # Get Specific URL Category by Name
    # =========================================================================
    - name: Get a specific URL category by name
      cdot65.scm.url_categories_info:
        name: "blocked-sites"
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
      register: named_category
      ignore_errors: true

    - name: Display named category details
      ansible.builtin.debug:
        var: named_category.url_categories
      when: named_category.url_categories is defined and named_category.url_categories | length > 0

    # =========================================================================
    # Get URL Categories from Different Containers
    # =========================================================================
    - name: Get URL categories in a specific snippet
      cdot65.scm.url_categories_info:
        snippet: "Security-Policy"
        scm_access_token: "{{ scm_access_token }}"
      register: snippet_categories
      ignore_errors: true

    - name: Display snippet categories
      ansible.builtin.debug:
        msg: "Found {{ snippet_categories.url_categories | length }} URL categories in snippet"
      when: snippet_categories.url_categories is defined

    - name: Get URL categories for a specific device
      cdot65.scm.url_categories_info:
        device: "firewall-01"
        scm_access_token: "{{ scm_access_token }}"
      register: device_categories
      ignore_errors: true

    - name: Display device categories
      ansible.builtin.debug:
        msg: "Found {{ device_categories.url_categories | length }} URL categories on device"
      when: device_categories.url_categories is defined

    # =========================================================================
    # Analyze URL Categories
    # =========================================================================
    - name: Find URL List type categories
      ansible.builtin.set_fact:
        url_list_categories: "{{ all_url_categories.url_categories | selectattr('type', 'equalto', 'URL List') | list }}"

    - name: Display URL List categories
      ansible.builtin.debug:
        msg: "Found {{ url_list_categories | length }} URL List type categories"

    - name: Find Category Match type categories
      ansible.builtin.set_fact:
        category_match_categories: "{{ all_url_categories.url_categories | selectattr('type', 'equalto', 'Category Match') | list }}"

    - name: Display Category Match categories
      ansible.builtin.debug:
        msg: "Found {{ category_match_categories | length }} Category Match type categories"

    - name: Find categories with many entries
      ansible.builtin.set_fact:
        large_categories: "{{ all_url_categories.url_categories | selectattr('list', 'defined') | selectattr('list', 'length', '>', 5) | list }}"

    - name: Display large categories
      ansible.builtin.debug:
        msg: "{{ item.name }} has {{ item.list | length }} entries"
      loop: "{{ large_categories }}"
      loop_control:
        label: "{{ item.name }}"
      when: large_categories | length > 0

    # =========================================================================
    # Display Summary
    # =========================================================================
    - name: Display URL categories summary
      ansible.builtin.debug:
        msg:
          - "=== URL Categories Summary ==="
          - "Total URL categories: {{ all_url_categories.url_categories | length }}"
          - "URL List type: {{ url_list_categories | length }}"
          - "Category Match type: {{ category_match_categories | length }}"
          - "Categories with >5 entries: {{ large_categories | length }}"
