---
# ============================================================================
# Example Playbook: Vulnerability Protection Profile Management
# ============================================================================
# This playbook demonstrates how to manage Vulnerability Protection profiles
# in Palo Alto Networks Strata Cloud Manager (SCM) using the cdot65.scm
# Ansible collection.
#
# Prerequisites:
#   - Ansible 2.14 or higher
#   - cdot65.scm collection installed
#   - Valid SCM credentials in vault.yml
#   - pan-scm-sdk Python package installed
#
# Usage:
#   ansible-playbook vulnerability_protection_profile.yml --vault-password-file .vault_pass
#
# ============================================================================

- name: Manage Vulnerability Protection Profiles in SCM
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vault.yml

  tasks:
    # =========================================================================
    # Authentication
    # =========================================================================
    - name: Authenticate with SCM
      ansible.builtin.include_role:
        name: cdot65.scm.auth

    # =========================================================================
    # Create Basic Vulnerability Protection Profile
    # =========================================================================
    - name: Create a basic Vulnerability Protection profile
      cdot65.scm.vulnerability_protection_profile:
        name: "Example-Basic-Vuln-Protection"
        description: "Basic vulnerability protection profile for demonstration"
        rules:
          - name: "block-critical-high-medium"
            severity:
              - "critical"
              - "high"
              - "medium"
            category: "any"
            cve:
              - "any"
            host: "any"
            vendor_id:
              - "any"
            threat_name: "any"
            packet_capture: "disable"
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: present
      register: basic_profile

    - name: Display basic profile creation result
      ansible.builtin.debug:
        var: basic_profile

    # =========================================================================
    # Create Advanced Vulnerability Protection Profile
    # =========================================================================
    - name: Create advanced Vulnerability Protection profile with multiple rules
      cdot65.scm.vulnerability_protection_profile:
        name: "Example-Advanced-Vuln-Protection"
        description: "Advanced vulnerability protection with granular control"
        rules:
          - name: "block-critical-high"
            severity:
              - "critical"
              - "high"
            category: "any"
            cve:
              - "any"
            host: "any"
            vendor_id:
              - "any"
            threat_name: "any"
            packet_capture: "single-packet"
            action:
              reset_both: {}
          - name: "alert-medium-low"
            severity:
              - "medium"
              - "low"
            category: "any"
            cve:
              - "any"
            host: "any"
            vendor_id:
              - "any"
            threat_name: "any"
            packet_capture: "disable"
            action:
              alert: {}
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: present
      register: advanced_profile

    - name: Display advanced profile creation result
      ansible.builtin.debug:
        var: advanced_profile

    # =========================================================================
    # Create CVE-Specific Profile
    # =========================================================================
    - name: Create profile targeting specific CVE (Log4Shell)
      cdot65.scm.vulnerability_protection_profile:
        name: "Example-Log4Shell-Protection"
        description: "Profile targeting CVE-2021-44228 (Log4Shell)"
        rules:
          - name: "block-log4shell"
            severity:
              - "critical"
            category: "code-execution"
            cve:
              - "CVE-2021-44228"
            host: "server"
            vendor_id:
              - "any"
            threat_name: "any"
            packet_capture: "extended-capture"
            action:
              block_ip:
                track_by: "source"
                duration: 3600
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: present
      register: cve_profile

    - name: Display CVE-specific profile creation result
      ansible.builtin.debug:
        var: cve_profile

    # =========================================================================
    # Create Profile with SQL Injection Protection
    # =========================================================================
    - name: Create profile for SQL injection protection
      cdot65.scm.vulnerability_protection_profile:
        name: "Example-SQL-Injection-Protection"
        description: "Profile targeting SQL injection attacks"
        rules:
          - name: "block-sql-injection-critical"
            severity:
              - "critical"
              - "high"
            category: "sql-injection"
            cve:
              - "any"
            host: "server"
            vendor_id:
              - "any"
            threat_name: "any"
            packet_capture: "single-packet"
            action:
              reset_both: {}
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: present
      register: sql_profile

    - name: Display SQL injection profile creation result
      ansible.builtin.debug:
        var: sql_profile

    # =========================================================================
    # Update Existing Profile
    # =========================================================================
    - name: Update basic profile with additional rule
      cdot65.scm.vulnerability_protection_profile:
        name: "Example-Basic-Vuln-Protection"
        description: "Updated basic vulnerability protection profile"
        rules:
          - name: "block-critical-high-medium"
            severity:
              - "critical"
              - "high"
              - "medium"
            category: "any"
            cve:
              - "any"
            host: "any"
            vendor_id:
              - "any"
            threat_name: "any"
            packet_capture: "disable"
          - name: "alert-informational"
            severity:
              - "informational"
            category: "any"
            cve:
              - "any"
            host: "any"
            vendor_id:
              - "any"
            threat_name: "any"
            packet_capture: "disable"
            action:
              alert: {}
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: present
      register: updated_profile

    - name: Display profile update result
      ansible.builtin.debug:
        var: updated_profile

    # =========================================================================
    # Cleanup (Optional)
    # =========================================================================
    - name: Delete example profiles (cleanup)
      cdot65.scm.vulnerability_protection_profile:
        name: "{{ item }}"
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
        state: absent
      loop:
        - "Example-Basic-Vuln-Protection"
        - "Example-Advanced-Vuln-Protection"
        - "Example-Log4Shell-Protection"
        - "Example-SQL-Injection-Protection"
      register: cleanup_results
      when: cleanup_profiles | default(false) | bool

    - name: Display cleanup results
      ansible.builtin.debug:
        var: cleanup_results
      when: cleanup_profiles | default(false) | bool

    # =========================================================================
    # Summary
    # =========================================================================
    - name: Display summary
      ansible.builtin.debug:
        msg:
          - "=== Vulnerability Protection Profile Management Summary ==="
          - "Basic Profile: {{ 'Created/Updated' if basic_profile.changed else 'No changes' }}"
          - "Advanced Profile: {{ 'Created/Updated' if advanced_profile.changed else 'No changes' }}"
          - "CVE-Specific Profile: {{ 'Created/Updated' if cve_profile.changed else 'No changes' }}"
          - "SQL Injection Profile: {{ 'Created/Updated' if sql_profile.changed else 'No changes' }}"
          - "Updated Profile: {{ 'Updated' if updated_profile.changed else 'No changes' }}"
          - "To cleanup test profiles, run with: -e cleanup_profiles=true"
