---
# ============================================================================
# Example Playbook: Vulnerability Protection Profile Information Retrieval
# ============================================================================
# This playbook demonstrates how to retrieve information about Vulnerability
# Protection profiles from Palo Alto Networks Strata Cloud Manager (SCM)
# using the cdot65.scm Ansible collection.
#
# Prerequisites:
#   - Ansible 2.14 or higher
#   - cdot65.scm collection installed
#   - Valid SCM credentials in vault.yml
#   - pan-scm-sdk Python package installed
#
# Usage:
#   ansible-playbook vulnerability_protection_profile_info.yml --vault-password-file .vault_pass
#
# ============================================================================

- name: Retrieve Vulnerability Protection Profile Information from SCM
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yml

  tasks:
    # =========================================================================
    # Authentication
    # =========================================================================
    - name: Authenticate with SCM
      ansible.builtin.include_role:
        name: cdot65.scm.auth

    # =========================================================================
    # Retrieve All Profiles
    # =========================================================================
    - name: Get all Vulnerability Protection profiles in Texas folder
      cdot65.scm.vulnerability_protection_profile_info:
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
      register: all_profiles

    - name: Display all profiles
      ansible.builtin.debug:
        msg:
          - "Found {{ all_profiles.vulnerability_protection_profiles | length }} Vulnerability Protection profiles"
          - "Profiles: {{ all_profiles.vulnerability_protection_profiles | map(attribute='name') | list }}"

    - name: Display detailed information for each profile
      ansible.builtin.debug:
        var: item
      loop: "{{ all_profiles.vulnerability_protection_profiles }}"
      loop_control:
        label: "{{ item.name }}"

    # =========================================================================
    # Retrieve Specific Profile by Name
    # =========================================================================
    - name: Get a specific profile by name
      cdot65.scm.vulnerability_protection_profile_info:
        name: "{{ all_profiles.vulnerability_protection_profiles[0].name }}"
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
      register: specific_profile
      when: all_profiles.vulnerability_protection_profiles | length > 0

    - name: Display specific profile details
      ansible.builtin.debug:
        msg:
          - "Profile Name: {{ specific_profile.vulnerability_protection_profiles[0].name }}"
          - "Description: {{ specific_profile.vulnerability_protection_profiles[0].description | default('N/A') }}"
          - "Folder: {{ specific_profile.vulnerability_protection_profiles[0].folder }}"
          - "Number of Rules: {{ specific_profile.vulnerability_protection_profiles[0].rules | length }}"
      when:
        - specific_profile is defined
        - specific_profile.vulnerability_protection_profiles | length > 0

    # =========================================================================
    # Analyze Profile Rules
    # =========================================================================
    - name: Analyze rules in all profiles
      ansible.builtin.set_fact:
        profile_analysis: "{{ profile_analysis | default([]) + [item | combine({'rule_count': item.rules | length})] }}"
      loop: "{{ all_profiles.vulnerability_protection_profiles }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Display profile analysis
      ansible.builtin.debug:
        msg:
          - "Profile: {{ item.name }}"
          - "  Rules: {{ item.rule_count }}"
          - "  Description: {{ item.description | default('No description') }}"
      loop: "{{ profile_analysis }}"
      loop_control:
        label: "{{ item.name }}"

    # =========================================================================
    # Find Profiles by Rule Criteria
    # =========================================================================
    - name: Find profiles with critical severity rules
      ansible.builtin.set_fact:
        critical_profiles: >-
          {{
            all_profiles.vulnerability_protection_profiles |
            selectattr('rules', 'defined') |
            selectattr('rules', 'sequence') |
            map('dict2items') |
            flatten |
            selectattr('value.rules', 'defined') |
            map(attribute='value') |
            selectattr('rules', 'sequence') |
            list
          }}
      when: all_profiles.vulnerability_protection_profiles | length > 0

    - name: Display profiles with rules
      ansible.builtin.debug:
        msg: "Found {{ all_profiles.vulnerability_protection_profiles | length }} profiles with defined rules"

    # =========================================================================
    # Export Profile Configuration
    # =========================================================================
    - name: Export profile configurations to JSON
      ansible.builtin.copy:
        content: "{{ all_profiles.vulnerability_protection_profiles | to_nice_json }}"
        dest: "/tmp/vulnerability_protection_profiles_export.json"
        mode: "0644"
      when: all_profiles.vulnerability_protection_profiles | length > 0

    - name: Display export location
      ansible.builtin.debug:
        msg: "Profile configurations exported to /tmp/vulnerability_protection_profiles_export.json"
      when: all_profiles.vulnerability_protection_profiles | length > 0

    # =========================================================================
    # Generate Profile Report
    # =========================================================================
    - name: Generate profile summary report
      ansible.builtin.set_fact:
        profile_report:
          total_profiles: "{{ all_profiles.vulnerability_protection_profiles | length }}"
          profiles: "{{ all_profiles.vulnerability_protection_profiles | map(attribute='name') | list }}"
          total_rules: >-
            {{
              all_profiles.vulnerability_protection_profiles |
              map(attribute='rules') |
              map('default', []) |
              map('length') |
              list |
              sum
            }}

    - name: Display profile summary report
      ansible.builtin.debug:
        msg:
          - "=== Vulnerability Protection Profile Summary ==="
          - "Total Profiles: {{ profile_report.total_profiles }}"
          - "Total Rules Across All Profiles: {{ profile_report.total_rules }}"
          - "Profile Names:"
          - "{{ profile_report.profiles | to_nice_yaml }}"

    # =========================================================================
    # Retrieve by ID (if available)
    # =========================================================================
    - name: Get profile by ID
      cdot65.scm.vulnerability_protection_profile_info:
        id: "{{ all_profiles.vulnerability_protection_profiles[0].id }}"
        scm_access_token: "{{ scm_access_token }}"
      register: profile_by_id
      when: all_profiles.vulnerability_protection_profiles | length > 0

    - name: Display profile retrieved by ID
      ansible.builtin.debug:
        msg:
          - "Retrieved profile by ID: {{ profile_by_id.vulnerability_protection_profiles[0].name }}"
          - "ID: {{ profile_by_id.vulnerability_protection_profiles[0].id }}"
      when:
        - profile_by_id is defined
        - profile_by_id.vulnerability_protection_profiles | length > 0
