---
- name: Authenticate with SCM using the auth role
  hosts: localhost
  gather_facts: no
  roles:
    - cdot65.scm.auth
  vars_files:
    - ../vault.yml

- name: Query SCM variable information using the established session
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display authentication info
      debug:
        msg: "Authenticated with token: {{ scm_access_token | default('No token available!', true) | truncate(15, true, '...') }}"

    - name: Create a variable
      cdot65.scm.variable:
        name: "$test-variable"
        folder: "Texas"
        value: "10.1.1.0/24"
        type: "ip-netmask"
        description: "Test network variable"
        scm_access_token: "{{ scm_access_token }}"
      register: test_variable

    - name: Show created variable info
      debug:
        var: test_variable

    - name: Get all variables
      cdot65.scm.variable_info:
        folder: "Texas"
        scm_access_token: "{{ scm_access_token }}"
      register: all_variables

    - name: Show all variable info
      debug:
        var: all_variables

#    - name: Get a specific variable by ID
#      cdot65.scm.variable_info:
#        id: "12345678-1234-1234-1234-123456789012"
#        scm_access_token: "{{ scm_access_token }}"
#      register: variable_details

    - name: Get a specific variable by name
      cdot65.scm.variable_info:
        folder: "Texas"
        name: "$test-variable"
        scm_access_token: "{{ scm_access_token }}"
      register: named_variable

    - name: Show named variable info
      debug:
        var: named_variable

    - name: Get variables by type
      cdot65.scm.variable_info:
        folder: "Texas"
        type: "ip-netmask"
        scm_access_token: "{{ scm_access_token }}"
      register: type_variables

    - name: Show type-filtered variables
      debug:
        var: type_variables

    - name: Remove a variable
      cdot65.scm.variable:
        folder: "Texas"
        name: "$test-variable"
        scm_access_token: "{{ scm_access_token }}"
        state: absent